version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    image: ${FRONT_IMAGE}
    depends_on:
      - back-socket
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - .:/app
      - /app/node_modules
      - /backend
    environment:
      - TZ=GMT-5
    env_file:
      - .env.cb-front
    networks:
      - cb-net

  back-rest:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: ${STAGE}
    image: ${BACK_IMAGE}
    hostname: ${BACK_HOST}
    depends_on:
      - nats
      # - es
    ports:
      - "${BACK_PORT}:8081"
      # - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./backend:/app
    environment:
      - TZ=GMT-5
    env_file:
      - .env.cb-back
    networks:
      - cb-net

  back-grpc:
    build:
      context: .
      dockerfile: back-grpc/Dockerfile
      target: ${STAGE}
    image: ${GRPC_IMAGE}
    hostname: ${GRPC_HOST}
    expose:
      - "${GRPC_GW_PORT}"
      - "${GRPC_PORT}"
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${GRPC_GW_PORT}:${GRPC_GW_PORT}"
    volumes:
      - ./back-grpc:/app
    environment:
      - TZ=GMT-5
    env_file:
      - .env.cb-back-grpc
    depends_on:
      - redis
    networks:
      - cb-net

  back-socket:
    build:
      context: .
      dockerfile: backend/Dockerfile.socket
      target: ${STAGE}
    image: ${SOCKET_IMAGE}
    hostname: ${SOCKET_HOST}
    depends_on:
      - back-rest
    ports:
      - "${SOCKET_PORT}:8081"
    volumes:
      - ./backend:/app
    environment:
      - TZ=GMT-5
    env_file:
      - .env.cb-back
      - .env
    networks:
      - cb-net

  nats:
    image: nats-streaming:alpine3.18
    restart: always
    hostname: ${NATS_HOST}
    volumes:
      - nats-data:/data
    networks:
      - cb-net
  redis:
    image: redis:7-alpine
    restart: always
    hostname: ${REDIS_HOST}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - cb-net

volumes:
  redis-data:
    driver: local
  nats-data:
    driver: local

networks:
  cb-net:
    driver: bridge
