

// Generated by https://quicktype.io

export interface Chatpdf {
    id: number;
    createdAt: string;
    updatedAt: string;
    name: string;
    key: string;
    userId: number;
    user: User;
}

export interface User {
    id: string;
    username: string | null;
    createdAt: string;
    updatedAt: string;
    firstName: string;
    lastName: string;
    email: string;
    gender: string;
    password: string;
    photo: string;
    phone: string;
    Status: "active" | "inactive";
}
